import { Poppins } from 'next/font/google';
import "./globals.css";
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600'],
  variable: '--font-poppins',
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="nl" className={poppins.variable}>
      <body className="font-sans">{children}</body>
    </html>
  );
}
